### ISSUE TITLE
No retract image

### ISSUE THREAD

**Issue by reeichert** [molon/MLInputDodger#12]
Hi, i install MLInputDodger on my swift project, and when the keyboard appear, just show me a gray space, without retract image, it's working fine, but has no image

**Comment by reeichert** [comment]
i change some things and now works nice!

this is what I did: 

inf MLInputDodgerRetractView.m I change this function

``` Objective-C
- (UIButton *)button
{
    if (!_button) {
        UIButton *button = [UIButton buttonWithType :UIButtonTypeCustom];
        //UIButton *button = [[UIButton alloc]init];
        [button setImage:[UIImage imageNamed:@"retract.png"] forState:UIControlStateNormal];
        [button addTarget:self action:@selector(retract) forControlEvents:UIControlEventTouchUpInside];

        button.layer.cornerRadius = 5.0f;
        button.layer.masksToBounds = NO;
        button.backgroundColor = [UIColor clearColor];
        button.layer.backgroundColor = [UIColor colorWithRed:0.906 green:0.910 blue:0.918 alpha:1.000].CGColor;
        button.layer.rasterizationScale = [UIScreen mainScreen].scale;

        _button = button;
    }
    return _button;
}

```

and I upload retract@x.png to my images.xcassets 

Thanks

**Comment by molon** [comment]
@reeichert thanks so much. I never realized the problem.
new commit:  https://github.com/molon/MLInputDodger/commit/7c7479413eabb641e40fa34211705430027a4f01
the problem description: https://github.com/CocoaPods/CocoaPods/issues/3226 
and I have updated to pod. :)
