### ISSUE TITLE
tableView中的使用问题

### ISSUE THREAD

**Issue by demoker** [molon/MLInputDodger#19]
如果我设置了tableview的footerView，那么键盘弹起的时候就会将footerView提到键盘之上，感觉有问题，请问下博主有什么解决方法吗？谢谢

**Comment by molon** [comment]
@demoker 这个我倒没有试过，不过想来的话。我的目的是在键盘弹起之后，滚动tableView的话还是能完整的显示全部内容。所以说如果footerView被遮盖的话也不合理啊。

**Comment by demoker** [comment]
感谢博主的回复，我想想其他的方法吧！

**Comment by molon** [comment]
@demoker 嗯，不客气。
但是如果是你说的是sectionFooterView遮挡了输入控件什么的话，直接设置下shiftHeight应该就能解决。

**Comment by demoker** [comment]
thx
