### ISSUE TITLE
iOS7小键盘按钮的图片加载不出来

### ISSUE THREAD

**Issue by demoker** [molon/MLInputDodger#20]
Hi，iOS7小键盘按钮的图片加载不出来，麻烦问下是什么问题呢？

**Comment by molon** [comment]
@demoker 可否描述的详细一点。这样我没法查问题啊。因为demo和我使用中没发生这种情况。

**Comment by TLcv** [comment]
键盘右上角的小键盘图标，可否手动隐藏或开启

**Comment by molon** [comment]
@TLcv 可以啊。有个开关属性。你瞅瞅，我在外面。

**Comment by TLcv** [comment]
恩呢，刚刚看到，谢谢啦！

**Comment by demoker** [comment]
@molon 我使用4s iOS7的系统安装之后弹出键盘，发现右上角的那个按钮没有图片，只是一个灰色的方块儿
![Uploading Screen Shot 2016-01-18 at 19.00.50.png…]()

**Comment by demoker** [comment]
![screen shot 2016-01-18 at 19 03 37](https://cloud.githubusercontent.com/assets/10993817/12389815/3c30a41a-be16-11e5-8757-54c918f8f8fb.png)

**Comment by molon** [comment]
@demoker 请问你是这个demo下载了直接运行就如此么？ 其他系统是否ok。

**Comment by demoker** [comment]
就是iOS7有问题，其他iOS89应该是ok的

**Comment by molon** [comment]
@demoker 非常感谢提交issue。是我犯了很低级的错误。 https://github.com/molon/MLInputDodger/pull/21
