### ISSUE TITLE
使用第三方键盘切换时的问题

### ISSUE THREAD

**Issue by TLcv** [molon/MLInputDodger#23]
在真机上使用搜狗键盘调节键盘高度后，在账号输入框切换到密码输入框后，键盘因为从第三方键盘切换到系统键盘，view顶部在切换时会有一段黑色背景的显现然后消失

**Comment by molon** [comment]
@TLcv 
1. 你的dodgeView是scrollView还是view
2. 你register dodgeView的时机是什么时候，register之后的originalYAsDodgeViewForMLInputDodger打印值是多少，之后有没有对此属性修改过。
3.可否搞个动图来我瞧瞧，我重现不了。用LICEcap可方便录制动图。

另外如果dodgeView不是scrollView时候，originalYAsDodgeViewForMLInputDodger是记录原View的y位置，然后无论view的frame这么变化其y值都不会大于originalYAsDodgeViewForMLInputDodger。
故理应不会有出现黑色背景的可能性（姑且这里认为黑色背景是window的颜色）。

所以不是太清楚你发生的情况。需要详细描述。

**Comment by TLcv** [comment]
1. dodgeView 是view
   2.在viewDidAppear时注册，注册之后值是64
   3.shiftHeightAsDodgeViewForMLInputDodger值设置为185，运行在iPhone6上，
   ![123](https://cloud.githubusercontent.com/assets/8739251/12505209/b608fccc-c11f-11e5-9f75-281cb6265263.gif)

**Comment by molon** [comment]
@TLcv 我嘞乖，倒腾了半天，我为啥不能做到切回原生，键盘还是用的搜狗啊。。扣扣 姚姚启叁贰贰贰肆贰。 可以加我我么细研究。

**Comment by molon** [comment]
fixed: https://github.com/molon/MLInputDodger/pull/24
原因是搜狗输入法会在切换输入框的瞬间给dodge view添加一个弹簧动画，所以只要在给dodge view设置新的frame之前移除此动画即可。
