### ISSUE TITLE
在UIScrollView添加时，通过Debug View Hierarchy查看，scrollView的区域并不是在键盘上方，而是原来的区域，导致滑动时的滑动条在透明的背景下方，麻烦查看一下这块

### ISSUE THREAD

**Issue by SnowWangj** [molon/MLInputDodger#25]

**Comment by molon** [comment]
https://github.com/molon/MLInputDodger/commit/80da5ec9223634ea480782d16df432457e86d58e
添加一个全局的动画伴随回调，例如可以方便的用此回调自动修正UIScrollView的scrollIndicatorInsets
https://github.com/molon/MLInputDodger/blob/044c9172d823720a3125ca3ae968e9d8b77f7c7f/Example/MLInputDodger/AppDelegate.m#L22
