### ISSUE TITLE
如果 textField在titleView上 会有向上漂移的现象

### ISSUE THREAD

**Issue by TWH-KKK** [molon/MLInputDodger#38]

**Comment by molon** [comment]
navigationBar的titleView么？ 你的dodgeView设置的是哪个。

**Comment by TWH-KKK** [comment]
dodgeView设置成 自定义的 titleView 放在 navigationBar上也会飘逸 
加了originalYAsDodgeViewForMLInputDodger = 7 解决了

**Comment by molon** [comment]
@TWH-KKK OK
