### ISSUE TITLE
UIScrollView 的内容未超过一屏幕时，输入框被键盘遮挡了

### ISSUE THREAD

**Issue by liuminisaboy** [molon/MLInputDodger#40]
UIScrollView 的内容未超过一屏幕时，输入框被键盘遮挡了

**Comment by molon** [comment]
@liusen001 
`ListViewController.m`里一部分代码我修改成了
```
- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];
    
    self.tableView.frame = CGRectMake(0, 200, CGRectGetWidth(self.view.frame),CGRectGetHeight(self.view.frame)-300);
}
```
去测试是OK。
麻烦给出你的测试代码帮助解决。

**Comment by liuminisaboy** [comment]
`_rootView.shiftHeightAsDodgeViewForMLInputDodger = 50.0f;
      
  [_rootView registerAsDodgeViewForMLInputDodgerWithOriginalContentInset:_rootView.contentInset];`

1，这是一个全屏的 scrollView，scrollView 上面有多个输入框，contentsize 没有超过scrollView.frame.height，这种情况下输入，并没有触发躲避键盘的行为；

2，设置 self.edgesForExtendedLayout = UIRectEdgeNone;  self.view的键盘躲避也有问题。

**Comment by molon** [comment]
@liusen001 抱歉，还是没能重现你所说的情况。可否fork一下仓库，然后修改部分代码重现下，我去解决。

**Comment by liuminisaboy** [comment]
@molon ，我已fork，新建了一个 vc ，你可以看下

**Comment by molon** [comment]
@liusen001 发生这种情况是因为你直接添加textField到scrollView上，而并未改动其contentSize这本身就是一个错误的行为。contentSize可以不超过scrollView.height但是一定要设置到才可以。
有问题再交流。 :)
```
- (void)loadTextField {
    for (int i = 0; i<6; i++) {
        UITextField* tf = [[UITextField alloc] initWithFrame:CGRectMake(20, 40+(44+20)*i, self.view.bounds.size.width-20, 44)];
        tf.backgroundColor = [UIColor grayColor];
        tf.placeholder = [NSString stringWithFormat:@"%d",i];
        [self.scrollView addSubview:tf];
        
        if (i==6-1) {
            self.scrollView.contentSize = CGSizeMake(self.view.frame.size.width, CGRectGetMaxY(tf.frame));
        }
    }
}
```

**Comment by liuminisaboy** [comment]
@molon OK，我知道了！
