### ISSUE TITLE
UITableViewController+MLInputDodger

### ISSUE THREAD

**Issue by eudaemonia2xl** [molon/MLInputDodger#41]
TableViewController 中使用MLInputDodger 底部会显示不全，键盘弹出收起知道，会导致TableViewController底部一行数据显示不完整

**Comment by molon** [comment]
@eudaemonia2xl 是在是抱歉，哥们，回复的有些晚了。
你这个问题是由于TableViewController原本有自己的躲避键盘的特性。这个特性和我的库有些冲突。暂时还不知道怎么去disable掉它的。建议使用UIViewController+UITableView的组合，比较自由。

**Comment by molon** [comment]
@eudaemonia2xl 稍微研究了一下。
你可以加这个category，然后就OK了，但是这个方法是私有方法哈，能不能上架我就不太清楚了。。
```
@implementation UITableView(DisableAutomaticKeyboard)
- (void)_adjustForAutomaticKeyboardInfo:(id)arg1 animated:(BOOL)arg2 lastAdjustment:(float*)arg3 {
    return;
}
@end
```
