### ISSUE TITLE
App crash when I touch a UIWebView

### ISSUE THREAD

**Issue by iwanglian** [molon/MLInputDodger#8]
I use the device of iOS9,  and there are a UITextField and a UIWebView in the View Controller,  and use the MLInputDodger.

When I touch the webview,  the app crash 
MLInputDodger.m  
- (void)setFirstResponderView:(UIView *)firstResponderView
  firstResponderView  donesnotRecognizeSelector setInputAccessoryView:

firstResponderView is kind of webview ,which has no setInputAccessoryView method.

So i add this code, and crash go away
'''
    if(![firstResponderView respondsToSelector:@selector(setInputAccessoryView:)]){
        return;
    }
 '''

**Comment by molon** [comment]
@iwanglian  thanks, buddy. it help me much.
